# Generated by Django 6.0 on 2025-12-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
