# Generated by Django 6.0 on 2025-12-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_visitor_is_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='is_invited',
            field=models.BooleanField(default=False),
        ),
    ]
