# Generated by Django 6.0 on 2025-12-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0003_visitor_is_invited'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='allow_join',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='queue',
            name='ask_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='queue',
            name='capacity',
            field=models.IntegerField(default=1000),
        ),
    ]
