# Generated by Django 6.0 on 2025-12-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0004_queue_allow_join_queue_ask_input_queue_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='status_language',
            field=models.CharField(choices=[('AUTO', 'Auto'), ('EN', 'English'), ('MS', 'Malay')], default='AUTO', max_length=10),
        ),
        migrations.AddField(
            model_name='queue',
            name='wait_time_display',
            field=models.CharField(choices=[('AUTO', 'Automatically calculated'), ('HIDDEN', 'Hidden')], default='AUTO', max_length=10),
        ),
    ]
