# Generated by Django 6.0 on 2026-01-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0005_queue_status_language_queue_wait_time_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='queue_logos/'),
        ),
    ]
