# Generated by Django 6.0.1 on 2026-01-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0006_queue_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='service_type',
            field=models.CharField(choices=[('A', 'Pendaftaran'), ('B', 'Pembayaran'), ('C', 'Pertanyaan')], default='A', max_length=1),
        ),
    ]
