# Generated by Django 6.0.1 on 2026-01-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queues", "0007_visitor_service_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queue",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nama Barisan"),
        ),
        migrations.AlterField(
            model_name="queue",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
