# Generated by Django 6.0.1 on 2026-01-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queues", "0008_alter_queue_name_alter_queue_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="served_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
