# Generated by Django 6.0.1 on 2026-02-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queues", "0009_visitor_served_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="queue",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="queue_videos/"),
        ),
    ]
