# Generated by Django 6.0.1 on 2026-02-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queues", "0010_queue_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="queue",
            name="stream_url",
            field=models.CharField(
                blank=True,
                help_text="Link Embed YouTube (Contoh: https://www.youtube.com/embed/live_stream_id)",
                max_length=500,
                null=True,
            ),
        ),
    ]
